Learning Numpy
---

This Notebook is for learning NumPy.
![CheatSheet](images/numpy_basics-1.png)

## Install and import the library

In [21]:
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


## Creating Arrays

Declare several arrays.
Print the shape of an array

In [98]:
a = np.array([1, 2, 3])
b = np.array([(1.5,2,3), (4,5,6)], dtype=float)
c = np.array([ [(1.5, 2,3), (4,5,6)],[(3,2,1),(4,5,6)] ], dtype=float)

print( "a=",a)
print("a.shape=",  a.shape)

print( "b=",b)
print("b.shape=",  b.shape)

print( "c=",c)
print("c.shape=",  c.shape)


a= [1 2 3]
a.shape= (3,)
b= [[1.5 2.  3. ]
 [4.  5.  6. ]]
b.shape= (2, 3)
c= [[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]
c.shape= (2, 2, 3)


### Initial Placeholders

In [19]:
zero_3x4 = np.zeros((3,4))   #Create an array of zeros
ones_2x3x4 = np.ones((2,3,4), dtype=np.int16) #Create an array of ones

# Create an array of evenly spaced values (step value)
d = np.arange(10,25,5)

# Create an array of evenly spaced values (number of samples)
l = np.linspace(0, 2, 9)

# Create a constant array
cons_2x2 = np.full((2,2), 7)

# Create a 2x2 identity matrix
eye_2x2 = np.eye(2)

# Create an array with randon values
rand_2x3 = np.random.random((2,3))

# Create an empty array
empt_3x2 = np.empty((3,2))

In [20]:
# test above cell
print(zero_3x4)
print(ones_2x3x4)
print(d)
print(l)
print(cons_2x2)
print(eye_2x2)
print(rand_2x3)
print(empt_3x2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[10 15 20]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.48819844 0.36997619 0.35003516]
 [0.29583019 0.84622805 0.11522176]]
[[0.02084922 0.09634677]
 [0.09962776 0.26809138]
 [0.20930318 0.69006832]]


## I/O

### Saving and Loading on Disk

In [22]:
np.save('my_array', a)
np.savez('array.npz', a, b)
_c, _d = np.load('array.npz')

In [23]:
# TODO: check save/savez details in refer
print(_c)
print(_d)

arr_0
arr_1


### Saving and Loading Text File

In [28]:
np.loadtxt('myfile.txt')
np.genfromtxt('mydata.csv', delimiter=', ')
np.savetxt('myarray.txt', a, delimiter=' ')

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: loadtxt: Empty input file: "myfile.txt"
  """Entry point for launching an IPython kernel.
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: genfromtxt: Empty input file: "mydata.csv"
  


In [29]:
print(a)

[1 2 3]


## Data Types

In [31]:
np.int64
np.float32
np.complex
np.bool
np.object
np.string_
np.unicode_

numpy.str_

## Inspecting Your Array

In [32]:
a.shape
len(a)
a.ndim
a.size
a.dtype
a.dtype.name
b.astype(int)

print(
a.shape,
len(a),
a.ndim,
a.size,
a.dtype,
a.dtype.name,
b.astype(int)
)

(3,) 3 1 3 int64 int64 [[1 2 3]
 [4 5 6]]


## Array Mathematics
### Arithmetic Operations

In [52]:
L = [
    a - b ,
    np.subtract(a,b) ,
    a + b ,
    np.add(a,b) ,
    np.divide(a,b),
    a / b,
    a * b,
    np.multiply(a,b),
    np.exp(b),
    np.sqrt(b),
    np.sin(b),
    np.cos(b),
    np.log(b),
    e.dot(f)
]

print(
    "\n\nSubstraction:\n", a - b,
    "\n\nSubstraction:\n", np.subtract(a, b)
)

print(
    "\n\nSubstraction:\n", L[0],
    "\n\nSubstraction:\n", L[1]
)

print(L)



Substraction:
 [[-0.5  0.   0. ]
 [-3.  -3.  -3. ]] 

Substraction:
 [[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]


Substraction:
 [[-0.5  0.   0. ]
 [-3.  -3.  -3. ]] 

Substraction:
 [[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]
[array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]]), array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]]), array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]]), array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]]), array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]]), array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]]), array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]]), array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]]), array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]]), array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]]), array([[ 0.99749499,  0.90929743,  0.14112001],
       [-0.7568025 , -0.9589242

### Comparison

In [54]:
L = [
    a == b,
    a < 2, 
    np.array_equal(a, b)
]
print(L)

[array([[False,  True,  True],
       [False, False, False]]), array([ True, False, False]), False]


### Aggregate Functions

In [59]:
L = [
    a,b,                   # a and b
    a.sum(),               # Array-wise sum
    a.min(),               # Array-wise minimum value
    b.max(axis=0),         # Maximum value of an array row
    b.cumsum(axis=1),      # Cumulative sum of the elements
    a.mean(),              # Mean
    #b.median(),           # Median
    #a.corrcoef(),         # Correlation coefficient
    np.std(d)              # Standard deviation
]

print(L)

[array([1, 2, 3]), array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]]), 6, 1, array([4., 5., 6.]), array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]]), 2.0, 4.08248290463863]


### Copying Arrays

In [62]:
# Create a view of the array with the same data
x1 = a.view()

# Create a copy of the array
x2 = np.copy(a)

# Create a deep copy of the array
x3 = a.copy()

print(x1, x2, x3)
print(type(x1))
print(type(x2))
print(type(x3))

[1 2 3] [1 2 3] [1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### Soring Arrays

In [71]:
aa = a
aa.sort()
print(aa)

# Sort the elements of an array's axis
cc = c
cc.sort(axis=0)
print(cc)

[1 2 3]
[[[1.5 2.  1. ]
  [4.  5.  6. ]]

 [[3.  2.  3. ]
  [4.  5.  6. ]]]


### Subsetting, Slicing, Indexing

In [75]:
L = [
# Subsetting
a[2],
b[1,2],

# Slicing
    # Select items at index 0 and 1
a[0:2],
    
    # Select items at rows 0 and 1 in column 1
b[0:2,1],
    
    # Select all items at row 0 (equivalent to b[0:1, :]) 
b[:1],
    
    # Same as [1,:,:]
c[1,...],
    
    # Reversed array a
a[: : -1],

# Boolean Indexing
    #Select elements from a less than 2
a[a<2],

# Fancy Indexing
b[[1,0,1,0],[0,1,2,0]],
    #Select a subset of the matrix’s rows and columns
b[[1,0,1,0]][:,[0,1,2,0]]
]

print(L)



[3, 6.0, array([1, 2]), array([2., 5.]), array([[1.5, 2. , 3. ]]), array([[3., 2., 3.],
       [4., 5., 6.]]), array([3, 2, 1]), array([1]), array([4. , 2. , 6. , 1.5]), array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])]


## Array Manipulation

### Transposing Array

In [ ]:
# Permute array dimensions
i = np.transpose(b)
i.T

### Changing Array Space 

In [91]:
# Flatten the array
b.ravel()
print(b)

# Reshape, but don’t change data
b.reshape(3,-2)
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


### Adding/Removing Elements

In [92]:
print(a)
a.resize((2,6)) # Return a new array with shape (2,6)
np.append(a,b)
np.insert(a, 1, 5)
np.delete(a, [1])
print(a)

[1 2 3]
[[1 2 3 0 0 0]
 [0 0 0 0 0 0]]


### Combining Arrays

In [93]:
print(a)
print(b)

[[1 2 3 0 0 0]
 [0 0 0 0 0 0]]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [102]:
#np.concatenate((a,b), axis=0)
np.vstack((a,b))
np.r_[e,f]
np.hstack((e,f))
#np.column_stack((a,d))
np.c_[a,d]

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

### Spitting Arrays

In [100]:
np.hsplit(a,3)
np.vsplit(c,2)

[array([[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 1.],
         [4., 5., 6.]]])]